### ISSUE TITLE
Output video length doesn't sync driving video

### ISSUE THREAD

**Issue by linthmwan** [megvii-research/megactor#21]
Hi, I use your sample code and run on test_data.
However, I found that the output video is only one second, but the driving video length is 6 seconds.

https://github.com/megvii-research/megactor/assets/114485232/ae3b2ee7-a41a-4561-b199-18351ab5471b

Is there any fps or frame rounding setting in the code that cause this issue?

**Comment by lhd777** [comment]
This is due to the limitation we placed on the length of the input driven in the online demo, owing to various constraints associated with it. You could simply remove the length limit, thereby enabling the generation of longer videos: https://github.com/megvii-research/megactor/blob/main/eval.py#L77

**Comment by linthmwan** [comment]
Nice~
Thank you for giving me the root cause.
